sudo: false

language: go

go:
  - 1.8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=kurio-dev
    - CLUSTER_NAME_STG=fibgo-cluster-stg
    - COMPUTE_ZONE=asia-east1-a
    - DOCKER_IMAGE_NAME_STG=fibweb-stg
    - KUBE_DEPLOYMENT_NAME=fibweb-deployment
    - KUBE_DEPLOYMENT_CONTAINER_NAME=fibweb
    - NODE_EV=CI

install:
  - go get -v ./...

before_script:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - docker network create fibnet
  - docker run -d --name fibgo --network fibnet uudashr/fibgo

script:
  - go test -v
  - gometalinter --deadline=15s
  - go install ./...
  - docker build -t fibweb .
  - docker run -d --name fibweb -p 127.0.0.1:8080:8080 -e FIBGO_ADDR=fibgo:8080 --network fibnet fibweb
  - curl --fail http://127.0.0.1:8080 || exit 1
  - curl --fail http://127.0.0.1:8080/api/fibonacci/numbers || exit 1

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
      curl https://sdk.cloud.google.com | bash;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: .travis/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: master

after_script:
  - docker stop fibweb && docker rm -v fibweb
  - docker stop fibgo && docker rm -v fibgo
  - docker network rm fibnet
