version: '3.1'
services:
  web:
    build: .
    depends_on:
      - fibgo
    environment:
      - FIBGO_ADDR=fibgo:8080
    ports:
      - "8080:8080"
    networks:
      - back-tier
  fibgo:
    image: uudashr/fibgo
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
