version: '3.1'
services:
  web:
    build: .
    depends_on:
      - fibgo
    environment:
      - FIBGO_ADDR=fibgo:8080
    ports:
      - "8080:8080"
    networks:
      - fibnet
  fibgo:
    image: uudashr/fibgo
    networks:
      - fibnet

networks:
  fibnet:
